### ISSUE TITLE
Why is this licensed Apache 2.0

### ISSUE THREAD

**Issue by xdevs23** [Kotlin/kmp-native-wizard#7]
If this is the only way to create projects, there is no way to create a project that is not Apache 2.0 licensed.

While Apache 2.0 is compatible with quite a few licenses and is not very restrictive, it's still being forced upon everyone who wants to use this template.

Also, a Copyright header is missing, so no one really knows who the copyright holder is.

**Comment by Skaldebane** [comment]
It's a literal _template_, not library. Just remove the license file and put your own. That shouldn't be a problem because:
1. This is exactly what you'd end up with if you try doing it yourself.
2. As you work on this, you'll probably do enough changes that there's no real tie back to this template (and again, it's a _template_, so I don't think any of the usual worries even apply here).

**Comment by Skaldebane** [comment]
Looking at the license, it itself is a template.
The copyright holder names are literally just placeholders, making it even clearer that the whole thing isn't binding in any way.

**Comment by xdevs23** [comment]
> Looking at the license, it itself is a template. The copyright holder names are literally just placeholders, making it even clearer that the whole thing isn't "legally" binding in any way.
> 
> But yeah, I agree that it should be removed altogether. I don't think that even a public domain one is suitable (or needed at all), as this is explicitly marked as a template and marketed as such by JetBrains. They're just using GitHub for easy storage / retrieval, otherwise this is no different than what's bundled with IntelliJ (so it doesn't fall under the same argument that "no license" = "copyrighted by default" like other projects/libraries).

I understand and I agree. In a practical sense, it does not matter, but this would, at least in theory, be a reason for \*insert enterprise name* to not use this as the licensing terms are either:

1. not clear or
2. [clear, as it is explicitly stated](https://github.com/Kotlin/kmp-native-wizard?tab=readme-ov-file#license) but Apache-2.0 may not be suitable

My suggestion is to license it under CC0 1.0 Universal or 0-BSD as that is practically making it public domain without relying on public domain laws directly. (For example, in Germany, you can't just give up your copyright and make it public domain).

Also, the [Gradle wrapper](https://github.com/Kotlin/kmp-native-wizard/blob/main/gradle/wrapper/gradle-wrapper.jar) does not have a license included, but given that Gradle is licensed under Apache-2.0, I assume the wrapper does, too, but I don't think that's an issue in this case.

I firmly believe two things should be done instead of providing a template:

* Provide a CLI that can bootstrap a project (like cargo init, go mod init, and various JS frameworks)
* Add project creation functionality to the IDE (it's first party, so I'm surprised it's not there yet)

The need to use a template like this makes me feel like there is a serious lack of investment into tooling.

**Comment by SebastianAigner** [comment]
Like mentioned in previous comments, the Apache 2.0 license file and its presence in the README were _part of the template_, not describing the template contents. I agree however that this was needlessly confusing, I've deleted the template `LICENSE` file and clarified the license in the `README`. Hope that clears it up!
